### ISSUE TITLE
Cannot import into pterodactyl

### ISSUE THREAD

**Issue by adrijanb** [ankit2951/pterodactyl-valheim#1]
Hey,

Somehow the Eggs is giving me errors while uploading. Could you try to fix it? 

https://bin.ptdl.co/fidhz/

**Comment by Igneous** [comment]
@adrijanb Not the author, and not 100% sure exactly why this is blowing up, but I can help get this imported for you if you haven't already figured it out:

If you take a look at the stacktrace, you can see it's blowing up here:
```
#1 /var/www/pterodactyl/app/Services/Eggs/Sharing/EggImporterService.php(108): implode()
```

Line 108 of EggImporterService has to do with parsing file_denylist (which the author supplies as an empty string). Remove the file_denylist line from the json file and try reimporting.

**Comment by adrijanb** [comment]
@Igneous Thanks for your fix. It is working!

**Comment by ankit2951** [comment]
It's merged now ty
